#! /usr/bin/env ruby

require('turkish_support')
require('json')
require('./kelime')
require('./app')

oyun = Kelime.new

loop do 
	
	sec = App.ana_menu

	case sec

	when "1"
		App.temizle

		sec = App.oyun_sonu until ["E", "A"].include? sec
		sec == "E" ? break : redo
	
	when "2"
		
		sec = App.oyun_sonu until ["E", "A"].include? sec
		sec == "E" ? break : redo
	
	when "3"
		App.temizle

		print "Eklemek istediğiniz kelime nedir?: "
		deger = gets.chomp.downcase

		oyun.kelime_ekle(deger)

		puts " "
		puts "Kelime başarılı bir şekide ekledi. Teşekkürler!"

		sec = App.oyun_sonu until ["E", "A"].include? sec
		sec == "E" ? break : redo

	when "E"
		break
	end
end