#! /usr/bin/env ruby

require('turkish_support')
require('terminal-color')
require('./kelime')
require('./app')

using TurkishSupport

def ana_uygulama(secim = nil)

	oyun = Kelime.new

	loop do 
		
		sec = secim.nil? ? App.ana_menu : secim

		case sec

		when "1"
			App.temizle

			print "Bir kullanıcı adı girin: "
			kullanici = gets.chomp.downcase

			print "Kaç harfli bir kelime tahmin etmek istiyorsunuz?: "
			harf = gets.chomp.to_i

			kelime = oyun.kac_harf harf
			kelime = kelime[rand(0...kelime.size)]
			kelime = kelime.chomp!
			kelime = kelime.upcase
			harfler = kelime.chars



			basari = 0
			puan = (harfler.size - 1) * 10
			j = 0
			kontrol = [0]
			loop do
				i = 0
				puts " "
				harfler.each do |c|
					print ("\t" + c) if kontrol.include? i
					print "\t*".yellow unless kontrol.include? i
					i += 1;
				end

				puts " "
				puts " "
				print "Tahmininiz: "
				tahmin = gets.chomp
				tahmin.upcase!

				if tahmin == kelime
					basari = 1
					break
				end
				
				j += 1
				kontrol << j	
				
				puan -= 10

				break if j == harfler.size - 1 
			end

			if basari == 1
				puts "TEBRİKLER #{kullanici}! Aranan kelimeyi buldunuz.".green
				puts "Kelime: #{kelime}".green
				puts "Kazandığınız Puan: #{puan}".green

			else
				puts "OYUN BİTTİ #{kullanici}!".red
				puts "Aranan kelimeyi bulamadınız.".red
				puts "Kelime #{kelime}".red
				puts "Kazandığınız Puan: #{puan}".red
			end


			sec = App.oyun_sonu("Tekrar Oynamak İçin T") until ["E", "A", "T"].include? sec
			sec == "E" ? break : sec == "A" ? redo : ana_uygulama("1")
		
		when "2"
			
			sec = App.oyun_sonu until ["E", "A"].include? sec
			sec == "E" ? break : redo
		
		when "3"
			App.temizle

			puts "En az 3 harften oluşan bir kelime girmeniz gerekmektedir."; puts " "
			print "Eklemek istediğiniz kelime nedir?: "
			deger = gets.chomp

			unless (deger.is_a? String and deger.length > 2)
				App.mesaj "HATA! Belirtilen şartlara uygun olmayan bir veri girdiniz."
			
			else
				oyun.kelime_ekle(deger)
				App.mesaj "HARİKA! Kelime başarılı bir şekide ekledi. Teşekkürler!"
			end

			sec = App.oyun_sonu until ["E", "A"].include? sec
			sec == "E" ? break : redo

		when "4"
			puts oyun.liste

		when "E"
			break
		end
	end
end

ana_uygulama