#! /usr/bin/env ruby

require('turkish_support')
require('terminal-color')
require('./kelime')
require('./app')

using TurkishSupport

def ana_uygulama(secim = nil)
	oyun = Kelime.new

	loop do 
		sec = secim.nil? ? App.ana_menu : secim

		case sec
		when "1"
			App.temizle

			print "Bir kullanıcı adı girin: ".bold.yellow
			kullanici = gets.chomp.downcase

			print "Kaç harfli bir kelime tahmin etmek istiyorsunuz?: ".bold
			harf = gets.chomp.to_i

			kelime = oyun.kac_harf harf
			kelime = kelime[rand(0...kelime.size)]
			kelime = kelime.chomp!
			kelime = kelime.upcase
			harfler = kelime.chars


			kontrol = Array.new
			random = [*0...harfler.size]
			rand = random[rand(0...random.size)]
			random.delete(rand)
			kontrol << rand

			basari = false
			puan = (harfler.size - 1) * 10
			j = 0

			loop do
				i = 0
				puts " "
				harfler.each do |c|
					print ("\t" + c.bold) if kontrol.include? i
					print "\t*".yellow unless kontrol.include? i
					i += 1;
				end

				puts " "
				puts " "
				print "Tahmininiz: ".bold.yellow
				tahmin = gets.chomp
				tahmin.upcase!

				if tahmin == kelime
					basari = true
					break
				end
				
				j += 1
				rand = random[rand(0...random.size)]
				random.delete(rand)
				kontrol << rand
				
				puan -= 10

				break if j == (harfler.size - 1) 
			end

			if basari
				puts " " 
				puts "-----------".bold
				puts "TEBRİKLER #{kullanici}! Aranan kelimeyi buldunuz.".bold.green
				puts "Kelime: #{kelime}".bold.yellow
				puts "Kazandığınız Puan: #{puan}".bold.magenta
			else
				puts " " 
				puts " " 
				puts "-----------".bold
				puts "OYUN BİTTİ #{kullanici.bold.yellow}!".bold.red
				puts "Aranan kelimeyi bulamadınız.".bold
				puts "Kelime: #{kelime.green}".bold.yellow
				puts "Kazandığınız Puan: #{puan}".bold.magenta
			end


			sec = App.oyun_sonu("Tekrar Oynamak İçin T") until ["E", "A", "T"].include? sec
			sec == "E" ? break : (sec == "A" ? redo : ana_uygulama("1"))
		when "2"
			sec = App.oyun_sonu until ["E", "A"].include? sec
			sec == "E" ? break : redo
		when "3"
			App.temizle

			puts "En az 3 harften oluşan bir kelime girmeniz gerekmektedir.".bold; puts " "
			print "Eklemek istediğiniz kelime nedir?: ".bold
			deger = gets.chomp

			unless (deger.is_a? String and deger.length > 2)
				App.mesaj "HATA! Belirtilen şartlara uygun olmayan bir veri girdiniz.".bold.red
			
			else
				oyun.kelime_ekle(deger)
				App.mesaj "HARİKA! Kelime başarılı bir şekide ekledi. Teşekkürler!".bold.green
			end

			sec = App.oyun_sonu until ["E", "A"].include? sec
			sec == "E".bold ? break : redo

		when "4"
			puts oyun.liste
		when "E"
			break
		end
	end
end

ana_uygulama